### PR TITLE
add support for .tsx components and add basic tsx templated

### PR DESCRIPTION
**Pull request by 8ACHIRA**
Added support for .tsx extension and added a template for a rafc tsx file.

### CODE REVIEW

**Comment by iamtabrezkhan** [comment]
Hi @8ACHIRA,

Thanks for your efforts. Your proposal looks good to me, but the only problem I see is that if I run this command without the extension, for instance: `rg c rafctsx hello-world` it will end up generating a `HelloWorld.js` file with the typescript template.

The approach that I have in mind is that we can keep commands as they are right now but add ts or tsx template files in the template folder. So, when generating a component the `--ext` option can decide which template to choose.

Lets say I ran this command `rg c rafc hello-world --ext ts`, now the `component.js` file in the `commands` folder can decide which template to choose. Now, in the `commands/component.js` `type` variable contains "rafc" string and `ext`
 variable has "ts" string, now we can decide the `templateName` variable base on the `ext`.

Please refer to the attached screenshot below.

Let me know if you have any questions.

rg

**Comment by iamtabrezkhan** [comment]
This way we don't have to add any extra types for the components instead let the extension decide which template to choose.

**Comment by 8ACHIRA** [comment]
> Hi @8ACHIRA,
> 
> Thanks for your efforts. Your proposal looks good to me, but the only problem I see is that if I run this command without the extension, for instance: `rg c rafctsx hello-world` it will end up generating a `HelloWorld.js` file with the typescript template.
> 
> The approach that I have in mind is that we can keep commands as they are right now but add ts or tsx template files in the template folder. So, when generating a component the `--ext` option can decide which template to choose.
> 
> Lets say I ran this command `rg c rafc hello-world --ext ts`, now the `component.js` file in the `commands` folder can decide which template to choose. Now, in the `commands/component.js` `type` variable contains "rafc" string and `ext`
> variable has "ts" string, now we can decide the `templateName` variable based on the `ext`.
> 
> Please refer to the attached screenshot below.
> 
> Let me know if you have any questions.
> 
> rg

**Comment by 8ACHIRA** [comment]
@iamtabrezkhan I am completely new to contributing so thanks for the feedback, I will have a look at implementing this later in the evening :)

**Pull request closed without merging**
